# Copyright (c) 2026 Forty5 Park. All Rights Reserved.
# Proprietary and confidential. See LICENSE.
"""`prime-mfr clean` — remove generated outputs to enable a clean re-run.

Default behaviour: removes all pipeline outputs (metrics, OOF predictions,
state pickles, logs, scratch dirs) while keeping the inputs the pipeline
needs to retrain:

  KEEP (inputs):
    artifacts/042026-*.parquet          (raw Yardi feeds)
    artifacts/best_params.json          (tuned LightGBM hyperparams — expensive to recompute)
    artifacts/best_catboost_params.json (tuned CatBoost hyperparams)
    pretraining_v2.parquet              (joined Yardi feed; cheap to regen)
    eda/atlanta_landmarks.json          (curated landmark coordinates)
    src/, configs/, tests/, docs/

  REMOVE (outputs):
    artifacts/stacking_scratch/          (OOF state pickles)
    artifacts/tune_cb_scratch/           (tuning scratch)
    artifacts/metrics*.json
    artifacts/oof_predictions*.parquet
    artifacts/feature_importance.csv
    artifacts/segment_tables.json
    artifacts/error_segmentation_report.md
    artifacts/run.log, stdout.log
    __pycache__/, .ruff_cache/, .pytest_cache/

Pass --deep to ALSO remove tuned hyperparams and pretraining_v2.parquet —
these can be regenerated by `prime-mfr tune` and `prime-mfr-pretrain`
respectively, but tuning takes ~45-60 minutes per learner.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from prime_mfr.core import ARTIFACTS_DIR, PROJECT_DIR


# Paths to remove on every `clean` run.
_OUTPUT_FILES_GLOB = [
    # Pipeline outputs
    "artifacts/metrics*.json",
    "artifacts/oof_predictions*.parquet",
    "artifacts/feature_importance.csv",
    "artifacts/segment_tables.json",
    "artifacts/error_segmentation_report.md",
    # Logs
    "artifacts/run.log",
    "artifacts/stdout.log",
    "artifacts/test.txt",
    # Optuna intermediate state (kept by default but regeneratable)
    "artifacts/optuna_journal.log*",
    "artifacts/optuna_study.db*",
    "artifacts/optuna_study.json",
    "artifacts/optuna_catboost_study.json",
    # Backups
    "artifacts/*.bak",
    "artifacts/*.json.bak",
]

_OUTPUT_DIRS = [
    "artifacts/stacking_scratch",
    "artifacts/tune_cb_scratch",
]

# Caches / build detritus everywhere in the repo.
_CACHE_PATTERNS = [
    "**/__pycache__",
    "**/.ruff_cache",
    "**/.pytest_cache",
    "**/.mypy_cache",
    "**/*.egg-info",
]

# Additional paths removed only with --deep.
_DEEP_FILES = [
    "artifacts/best_params.json",
    "artifacts/best_catboost_params.json",
    "pretraining_v2.parquet",
    "pretraining.parquet",
]


def register(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "clean",
        help="Remove generated outputs (keeps source data + tuned hyperparams).",
        description=(
            "Remove pipeline outputs, state pickles, logs, and caches. "
            "Source parquets and tuned hyperparameters are preserved by default. "
            "Use --deep to also remove tuned hyperparams + pretraining_v2 (forces full re-tune)."
        ),
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be deleted without actually deleting.",
    )
    p.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt.",
    )
    p.add_argument(
        "--deep",
        action="store_true",
        help="Also remove tuned hyperparams and pretraining_v2.parquet.",
    )
    p.set_defaults(func=run)


def _collect_targets(*, deep: bool) -> list[Path]:
    """Resolve all paths slated for deletion."""
    targets: list[Path] = []

    for pattern in _OUTPUT_FILES_GLOB:
        targets.extend(PROJECT_DIR.glob(pattern))

    for d in _OUTPUT_DIRS:
        path = PROJECT_DIR / d
        if path.exists():
            targets.append(path)

    for pattern in _CACHE_PATTERNS:
        targets.extend(PROJECT_DIR.glob(pattern))

    if deep:
        for f in _DEEP_FILES:
            path = PROJECT_DIR / f
            if path.exists():
                targets.append(path)

    # Deduplicate while preserving order.
    seen: set[Path] = set()
    unique: list[Path] = []
    for t in targets:
        resolved = t.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique.append(t)
    return unique


def _format_size(n_bytes: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n_bytes < 1024:
            return f"{n_bytes:>6.1f} {unit}"
        n_bytes /= 1024  # type: ignore[assignment]
    return f"{n_bytes:>6.1f} TB"


def _size_of(path: Path) -> int:
    if path.is_file():
        try:
            return path.stat().st_size
        except OSError:
            return 0
    if path.is_dir():
        total = 0
        for p in path.rglob("*"):
            if p.is_file():
                try:
                    total += p.stat().st_size
                except OSError:
                    pass
        return total
    return 0


def run(args: argparse.Namespace) -> int:
    targets = _collect_targets(deep=args.deep)

    if not targets:
        print("Nothing to clean. Repo is already pristine.")
        return 0

    print(f"Found {len(targets)} target(s) to remove" + (" [DEEP]" if args.deep else "") + ":")
    print()
    total_bytes = 0
    for t in targets:
        size = _size_of(t)
        total_bytes += size
        rel = t.relative_to(PROJECT_DIR) if t.is_relative_to(PROJECT_DIR) else t
        kind = "dir" if t.is_dir() else "file"
        print(f"  {_format_size(size)}  [{kind:>4s}]  {rel}")
    print()
    print(f"Total: {_format_size(total_bytes)}")
    print()

    if args.dry_run:
        print("(dry-run — nothing deleted)")
        return 0

    if not args.yes:
        try:
            answer = input("Delete these? [y/N] ").strip().lower()
        except EOFError:
            answer = "n"
        if answer not in ("y", "yes"):
            print("Aborted.")
            return 1

    deleted = 0
    failed: list[tuple[Path, str]] = []
    for t in targets:
        try:
            if t.is_dir():
                shutil.rmtree(t)
            else:
                t.unlink()
            deleted += 1
        except OSError as exc:  # noqa: BLE001
            failed.append((t, str(exc)))

    print(f"Deleted {deleted} target(s).")
    if failed:
        print(f"WARN: {len(failed)} failure(s):")
        for path, reason in failed:
            print(f"  {path}: {reason}")
        return 1

    # Ensure artifacts/ still exists for downstream prep.
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    return 0
